FROM pytorch/pytorch

WORKDIR /aid_app_env

COPY requirements.txt .

# Combine conda install commands and clean up to reduce image size.
# steps are broken down in order to determine any issues with specific packages
RUN conda install -c conda-forge "transformers==4.35.0" chromadb  

RUN conda install sentencepiece pandas flask gensim seaborn scikit-learn scikit-image pymssql h5py unidecode jupyter

RUN pip install --no-cache-dir --upgrade -r requirements.txt

RUN conda clean -afy

# COPY ./output/_models /aid_app/output/_models
# COPY ./output/_data/gensim-data /aid_app/output/_data/gensim-data

ENV TZ=Europe/Bucharest \
    SHOW_PACKS=Yes \
    FORCE_CPU=No \
    AID_APP_DOCKER=Yes \
    AID_APP_ID=BaseAidApp \
    AID_APP_ENV=v1.2

# Set the timezone based on the TZ environment variable
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# cannot combine with above RUN command due to the TZ variable not being set yet
RUN apt-get update && apt-get install -y \
    iputils-ping \
    tzdata \
    nano \
    vim \
    curl \
    git \
    htop \
    # Clean up apt cache to reduce image size
    && apt-get clean && rm -rf /var/lib/apt/lists/*    
