FROM pytorch/pytorch

WORKDIR /aid_app_env

COPY requirements.txt .

# Combine conda install commands and clean up to reduce image size.
RUN conda install -c conda-forge "transformers>=4.34.0" chromadb pandas flask gensim seaborn scikit-learn scikit-image pymssql h5py unidecode sentencepiece \
    && pip install --no-cache-dir --upgrade -r requirements.txt \
    && conda clean -afy

# COPY ./output/_models /aid_app/output/_models
# COPY ./output/_data/gensim-data /aid_app/output/_data/gensim-data

ENV TZ=Europe/Bucharest \
    AID_APP_DOCKER=Yes \
    SHOW_PACKS=Yes \
    FORCE_CPU=No \
    AID_APP_ID=BaseAidApp \
    ENV_VER=0.1.1