FROM pytorch/pytorch

RUN conda install pandas flask transformers datasets gensim seaborn scikit-learn scikit-image pymssql h5py unidecode sentencepiece
RUN pip install peft

WORKDIR /aid_app


# COPY ./output/_models /aid_app/output/_models
# COPY ./output/_data/gensim-data /aid_app/output/_data/gensim-data

ENV TZ Europe/Bucharest

ENV AID_APP_DOCKER Yes
ENV SHOW_PACKS Yes
ENV FORCE_CPU No
ENV AID_APP_ID BaseAidApp
